---
- name: Add Percona repository key
  become: yes
  become_user: root
  apt_key: keyserver=keys.gnupg.net id=9334A25F8507EFA5 state=present

- name: Add Percona repository
  become: yes
  become_user: root
  apt: deb="https://repo.percona.com/apt/percona-release_{{release_version}}.{{ansible_distribution_release}}_all.deb"

- name: Install Percona MySQL Server
  become: yes
  become_user: root
  apt:
    pkg:
      - python3-mysqldb
      - percona-server-server-5.7
      - percona-server-client-5.7
      - percona-toolkit
      - percona-xtrabackup
      - python-mysqldb
    state: present

- name: "Set the root password"
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: Create databases
  mysql_db:
    name: "{{ mysql_databases }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    
- name: "Create user {{ item.key }}"
  mysql_user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    host: "{{ item.value.host }}"
    state: present
    update_password: on_create
    priv: "{{ item.value.priv }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
  with_dict: "{{ mysql_users }}"


- name: Copy MySQL configuration
  template:
    src: mysqld.cnf.j2
    dest:
      /etc/mysql/percona-server.conf.d/mysqld.cnf
  notify:
    - restart mysql
